'use client';
import { useEffect, useRef, useState, type ChangeEvent } from 'react';
import SessionShell, { type SessionProps } from './art-sessions';
import { type Phase, type Exhibition, type Invitation } from './art-session-model';
import { ArtPreview, DrawingSurface, Icon, type Region } from './art-canvas';
import { WIDTH, HEIGHT, PAPERS, TOOLS, appendMark, artworkImage, artworkRegionImage, hasMarks, newArtwork, nextQuestionStyle, redo, uid, undo, type Artwork, type Journey, type Mark, type Tool } from './art-engine';
import './art-studio.css';
import './art-pc.css';
type View = 'home' | 'studio' | 'gallery' | 'exhibition';
const COLORS = ['#27232c', '#273bbe', '#e96248', '#dab33e', '#5e7160', '#a393bd', '#f3ede0', '#713d4d'];
const material: Record<Tool, { name: string; width: number; opacity: number; note: string }> = { ink: { name: '墨迹', width: 14, opacity: 1, note: '流动而有力度，慢下来时更饱满。' }, pastel: { name: '色粉', width: 42, opacity: .86, note: '让颗粒留在纸上，反复叠加会更浓。' }, charcoal: { name: '炭笔', width: 32, opacity: .8, note: '松散的炭粒，保留犹疑和断裂。' }, wash: { name: '色洗', width: 96, opacity: .68, note: '透明的宽色带，适合叠出空气和层次。' }, thread: { name: '游丝', width: 14, opacity: .9, note: '几根纤细的线，一起游走。' }, eraser: { name: '擦除', width: 64, opacity: 1, note: '擦去笔触，让纸重新露出来。' } };
function download(content: string, name: string, type = 'application/json') { const link = document.createElement('a'); const url = content.startsWith('data:') ? content : URL.createObjectURL(new Blob([content], { type })); link.href = url; link.download = name; link.click(); if (!content.startsWith('data:')) setTimeout(() => URL.revokeObjectURL(url), 1000); }
function errorText(error: unknown) { return error instanceof Error ? error.message : '这一步没有完成，请再试一次。'; }
function toggle(list: string[], id: string) { return list.includes(id) ? list.filter(value => value !== id) : [...list, id]; }
function Brand({ onClick }: { onClick: () => void }) { return <button className="art-brand" onClick={onClick} aria-label="Aether 返回主页"><span className="art-brand-symbol">æ</span><span>Aether<small>灵魂对话</small></span></button>; }
export default function ArtStudio() { return <SessionShell>{props => <StudioSession {...props} />}</SessionShell>; }
function StudioSession({ session, initialView, saveState, onUpdate, onManage, onNew, onImport, onExportAll, sidebar }: SessionProps) {
  const sessionId = session.id;
  const [phase,setPhase] = useState<Phase>(session.phase),[brief,setBrief] = useState(session.brief);

  const [view, setView] = useState<View>(initialView), [journey, setJourney] = useState<Journey>(session.journey), [activeId, setActiveId] = useState(session.activeId);
  const [tool, setTool] = useState<Tool>('pastel'), [color, setColor] = useState(COLORS[1]), [width, setWidth] = useState(42), [opacity, setOpacity] = useState(.86);
  const [mobilePane, setMobilePane] = useState<'canvas' | 'chat'>(session.phase === 'creating' ? 'canvas' : 'chat'), [focusCanvas, setFocusCanvas] = useState(false), [selecting, setSelecting] = useState(false), [region, setRegion] = useState<Region>();
  const [draft, setDraft] = useState(session.draft), [busy, setBusy] = useState(false), [status, setStatus] = useState(''), [notice, setNotice] = useState(''), [error, setError] = useState('');
  const [settings, setSettings] = useState(false), [questionStyle, setQuestionStyle] = useState<'natural' | 'fewer' | 'none'>(session.questionStyle), [invitation, setInvitation] = useState<Invitation | null>(session.invitation);
  const [exhibition, setExhibition] = useState<Exhibition>(session.exhibition), [exhibitIndex, setExhibitIndex] = useState(0);
  const dialogRef = useRef<HTMLElement>(null);
  const requestRef = useRef<AbortController | null>(null), bottomRef = useRef<HTMLDivElement>(null), importRef = useRef<HTMLInputElement>(null), uploadRef = useRef<HTMLInputElement>(null), composerRef = useRef<HTMLTextAreaElement>(null);
  const art = journey.artworks.find(item => item.id === activeId);
  const works = journey.artworks.filter(hasMarks);
  const exhibitWorks = exhibition.works.map(id => journey.artworks.find(item => item.id === id)).filter((item): item is Artwork => Boolean(item));
  const exhibitArt = exhibitWorks[Math.min(exhibitIndex, Math.max(0, exhibitWorks.length - 1))];
  const savedQuotes = journey.messages.filter(message => exhibition.quotes.includes(message.id));
  function patchArtwork(id: string, change: (current: Artwork) => Artwork) { setJourney(current => ({ ...current, artworks: current.artworks.map(item => item.id === id ? change(item) : item) })); }
  function stop() { requestRef.current?.abort(); requestRef.current = null; setBusy(false); setStatus(''); setJourney(current => ({ ...current, messages: current.messages.filter(message => message.content) })); }
  function addArtwork(source?: Artwork) { const next = source ? { ...source, id: uid(), title: source.title + ' · 继续', parentId: source.id, origin: source.origin === 'aether' ? 'dialogue' as const : source.origin, redo: [], createdAt: new Date().toISOString() } : newArtwork(art?.paper); setJourney(current => ({ ...current, id: current.id || uid(), artworks: [...current.artworks, ...(source ? [{ ...(current.artworks.find(item => item.id === source.id) || source), id: next.id, title: next.title, parentId: source.id, origin: next.origin, redo: [], createdAt: next.createdAt }] : [next])] })); setActiveId(next.id); setRegion(undefined); setSelecting(false); setView('studio'); setPhase('creating'); setMobilePane('canvas'); setInvitation(null); }
  function goCreate(prompt?: string) { setBrief(prompt || invitation?.prompt || journey.messages.filter(m=>m.role==='user').at(-1)?.content.slice(0,220) || brief); if (!art) addArtwork(); setPhase('creating'); setView('studio'); setMobilePane('canvas'); setFocusCanvas(false); setInvitation(null); }
  function enter(drawFirst = false) { if (drawFirst) goCreate(); else { setView('studio'); setMobilePane(phase === 'creating' ? 'canvas' : 'chat'); } setFocusCanvas(false); }
  function manageJourneys() { stop(); onManage(); }
  function beginNewJourney() { stop(); onNew(); }
  function finishJourney() { stop(); setPhase('completed'); setRegion(undefined); setSelecting(false); }

  function selectArtwork(id: string) { setActiveId(id); setRegion(undefined); setSelecting(false); setView('studio'); setPhase('reflection'); setMobilePane('chat'); }
  function changeTool(next: Tool) { setTool(next); setWidth(material[next].width); setOpacity(material[next].opacity); setSelecting(false); }
  function keepMark(mark: Mark) { if (art) patchArtwork(art.id, current => appendMark(current, mark)); }
  function exportJourney() { download(JSON.stringify({ format:'aether-session',version:3,session:{...session,journey,exhibition,activeId,phase,brief,draft,questionStyle,invitation} }, null, 2), (session.title || 'aether-journey') + '.json'); setNotice('旅程已导出，包含可编辑笔触、作品与对话。'); }
  async function readJourney(event: ChangeEvent<HTMLInputElement>) { stop(); await onImport(event); }
  async function uploadArtwork(event: ChangeEvent<HTMLInputElement>) {
    const file = event.target.files?.[0]; event.target.value = ''; if (!file) return;
    try { if (!['image/png','image/jpeg','image/webp'].includes(file.type) || file.size > 12_000_000) throw new Error('请选择 12 MB 以内的 PNG、JPEG 或 WebP 图片。'); const bitmap = await createImageBitmap(file); const canvas = document.createElement('canvas'); canvas.width = WIDTH; canvas.height = HEIGHT; const ctx = canvas.getContext('2d'); if (!ctx) throw new Error('当前浏览器无法打开图片。'); const ratio = Math.min(WIDTH / bitmap.width, HEIGHT / bitmap.height); ctx.drawImage(bitmap, (WIDTH - bitmap.width * ratio)/2, (HEIGHT - bitmap.height * ratio)/2, bitmap.width * ratio, bitmap.height * ratio); bitmap.close(); const next = { ...newArtwork(), title: file.name.replace(/\.[^.]+$/, '').slice(0,80), baseImage: canvas.toDataURL('image/png') }; setJourney(current => ({ ...current, id: current.id || uid(), artworks: [...current.artworks, next] })); setActiveId(next.id); setRegion(undefined); setView('studio'); setPhase('creating'); setMobilePane('canvas'); } catch (err) { setError(errorText(err)); }
  }
  async function savePng(current: Artwork) { try { download(await artworkImage(current, 1600), current.title + '.png'); } catch (err) { setError(errorText(err)); } }
  async function sendMessage(text: string, artworkMode = false) {
    const content = text.trim(); if (!content || busy || requestRef.current) return;
    if (artworkMode || region) setPhase('reflection');
    if (!journey.messages.some(m => m.role === 'user') && session.title === '一段新的相遇') onUpdate(sessionId,{title:content.replace(/\s+/g,' ').slice(0,24)});
    const nextStyle = nextQuestionStyle(content, questionStyle); setQuestionStyle(nextStyle);
    setError(''); setNotice(''); setDraft(''); setInvitation(null); setFocusCanvas(false); setMobilePane('chat');
    const userId = uid(), replyId = uid(), controller = new AbortController(); requestRef.current = controller; setBusy(true); setStatus('Aether 正在认真看…');
    const sourceArt = art, sourceRegion = region, history = [...journey.messages.filter(message => message.content), { id: userId, role: 'user' as const, content, ...(art && hasMarks(art) ? { artworkId: art.id } : {}) }];
    setJourney(current => ({ ...current, id: current.id || uid(), messages: [...current.messages, history[history.length - 1], { id: replyId, role: 'assistant', content: '', ...(sourceArt && hasMarks(sourceArt) ? { artworkId: sourceArt.id } : {}) }] }));
    let reader: ReadableStreamDefaultReader<Uint8Array> | undefined;
    try {
      const contextWorks = [...works.filter(item => item.id !== sourceArt?.id).slice(-1), ...(sourceArt && hasMarks(sourceArt) ? [sourceArt] : [])];
      const images = await Promise.all(contextWorks.map(async item => ({ id: item.id, title: item.title, image: await artworkImage(item, 800), isCurrent: item.id === sourceArt?.id })));
      const focusedImage = sourceRegion && sourceArt ? await artworkRegionImage(sourceArt, sourceRegion) : undefined;
      if (requestRef.current !== controller) return;
      const response = await fetch('/api/aether', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ mode: artworkMode || sourceRegion ? 'artwork' : 'conversation', phase: artworkMode || sourceRegion ? 'reflection' : phase, messages: history.map(({ role, content }) => ({ role, content })), artworks: images, preferences: { questionStyle: nextStyle }, ...(sourceRegion ? { focus: { image: focusedImage, x: sourceRegion.x / WIDTH, y: sourceRegion.y / HEIGHT, w: sourceRegion.w / WIDTH, h: sourceRegion.h / HEIGHT } } : {}) }), signal: controller.signal });
      if (!response.ok) { const result = await response.json().catch(() => ({})); throw new Error(result.message || 'Aether 暂时没有回应，请稍后重试。'); }
      if (!response.body) throw new Error('回应没有连接成功。');
      reader = response.body.getReader(); const decoder = new TextDecoder(); let buffer = '', answer = '', completed = false;
      while (true) {
        const { value, done } = await reader.read(); if (requestRef.current !== controller) return; buffer += decoder.decode(value, { stream: !done }); const frames = buffer.split(/\r?\n/); buffer = done ? '' : frames.pop() || '';
        for (const line of frames) {
          if (!line.startsWith('data:')) continue; const data = line.slice(5).trim(); if (!data) continue; if (data === '[DONE]') { completed = true; continue; }
          const event = JSON.parse(data);
          if (event.type === 'error') throw new Error(event.message || '回应中断了。');
          if (event.type === 'delta' && typeof event.text === 'string') { answer += event.text; const snapshot = answer; setStatus(''); setJourney(current => ({ ...current, messages: current.messages.map(message => message.id === replyId ? { ...message, content: snapshot } : message) })); }
          if (event.type === 'control' && event.inviteToCreate && event.invitation && typeof event.invitation.title === 'string' && typeof event.invitation.prompt === 'string') setInvitation(event.invitation);
        }
        if (done) break;
      }
      if (!completed || !answer) throw new Error('回应中断了，可以继续告诉 Aether 你的想法。');
    } catch (err) { if (requestRef.current === controller && !controller.signal.aborted) { setError(errorText(err)); setDraft(content); } }
    finally { if (reader) void reader.cancel().catch(() => {}); if (requestRef.current === controller) { requestRef.current = null; setBusy(false); setStatus(''); setJourney(current => ({ ...current, messages: current.messages.filter(message => message.content) })); } }
  }
  useEffect(() => { bottomRef.current?.scrollIntoView({ block: 'nearest', behavior: 'smooth' }); }, [journey.messages, busy]);
  useEffect(() => { onUpdate(sessionId,{journey,activeId,phase,brief,draft,questionStyle,invitation,exhibition}); },[sessionId,journey,activeId,phase,brief,draft,questionStyle,invitation,exhibition,onUpdate]);
  useEffect(() => () => { requestRef.current?.abort(); }, []);
  useEffect(() => { if (!notice) return; const timeout = setTimeout(() => setNotice(''), 5500); return () => clearTimeout(timeout); }, [notice]);
  useEffect(() => {
    if (!settings) return;
    const previous = document.activeElement instanceof HTMLElement ? document.activeElement : null;
    const dialog = dialogRef.current;
    const focusables = () => Array.from(dialog?.querySelectorAll<HTMLElement>('button:not(:disabled),select,input:not([hidden]),textarea,[tabindex="0"]') || []);
    focusables()[0]?.focus();
    const keyboard = (event: KeyboardEvent) => { if (event.key === 'Escape') { event.preventDefault(); setSettings(false); } if (event.key === 'Tab') { const items = focusables(), first = items[0], last = items.at(-1); if (event.shiftKey && document.activeElement === first) { event.preventDefault(); last?.focus(); } else if (!event.shiftKey && document.activeElement === last) { event.preventDefault(); first?.focus(); } } };
    document.addEventListener('keydown', keyboard);
    return () => { document.removeEventListener('keydown', keyboard); if (previous?.isConnected) previous.focus(); };
  }, [settings]);
  return <main className={'art-app art-view-' + view}>
    <input ref={importRef} type="file" accept=".json,application/json" hidden onChange={readJourney} aria-label="导入 Aether 旅程" />
    <input ref={uploadRef} type="file" accept="image/png,image/jpeg,image/webp" hidden onChange={uploadArtwork} aria-label="导入作品图片" />
    {view === 'home' ? <>
      <div className="art-original-cover" role="img" aria-label="Aether 灵魂对话，一张漂浮在深色宇宙中的抽象作品" />
      <div className="art-original-shade" />
      <header className="art-original-nav"><Brand onClick={()=>setView('home')} /><nav aria-label="主导航"><button onClick={manageJourneys}>对话记录</button><button onClick={()=>setView('gallery')}>作品空间</button><button onClick={()=>setSettings(true)} aria-label="打开偏好设置"><Icon name="settings" /></button></nav></header>
      <div className="art-original-entry"><button onClick={journey.messages.length || works.length ? beginNewJourney : ()=>enter(false)}>开始一段对话 <Icon name="arrow" /></button>{journey.messages.length || works.length ? <button className="art-original-continue" onClick={()=>enter(false)}>继续上一次</button> : null}</div>
      <footer className="art-original-footer"><span>作品不会替你定义自己</span><span>© 2026 Aether</span></footer>
    </> : <>
      <aside className="art-session-dock" aria-label="会话管理">{sidebar}</aside>
      {view === 'studio' ? <section className={'art-studio art-phase-' + phase + ' ' + (focusCanvas ? 'art-focused ' : '') + 'art-mobile-' + mobilePane}>
        <header className="art-studio-header"><div><span className="art-eyebrow">A JOURNEY WITH AETHER</span><input className="art-title-input" aria-label="旅程名称" value={session.title} maxLength={100} onChange={event=>onUpdate(sessionId,{title:event.target.value})} /></div><div className="art-header-actions"><span className="art-save-status" role="status">{saveState}</span><button className="art-mobile-sessions" onClick={manageJourneys}><Icon name="chat" /><span>对话记录</span></button><button onClick={()=>setView('gallery')} aria-label="作品空间"><Icon name="grid" /></button><button onClick={finishJourney} disabled={phase==='completed'}>先到这里</button></div></header>

        <div className={'art-mobile-switch ' + (phase === 'creating' ? 'art-hide-switch' : '')} role="group" aria-label="切换工作区域"><button aria-pressed={mobilePane === 'canvas'} onClick={() => setMobilePane('canvas')}>画布</button><button aria-pressed={mobilePane === 'chat'} onClick={() => setMobilePane('chat')}>对话 {busy ? '·' : ''}</button></div>
        {phase === 'creating' && art ? <section className="art-creation" aria-label="材料实验室与画布">
          {brief ? <div className="art-creative-brief"><span>从刚才的交流出发</span><p>{brief}</p></div> : null}<div className="art-artwork-title-row"><input aria-label="作品标题" value={art.title} maxLength={80} onChange={event=>patchArtwork(art.id,current=>({...current,title:event.target.value}))} /><button onClick={()=>{setPhase(works.length?'reflection':'dialogue');setMobilePane('chat');}}>先回到交流</button></div><div className="art-canvas-top"><span>{selecting ? '拖动框选一处，也可以用右侧选项选择位置。' : '不必想好，先留下一笔。'}</span><div><button disabled={!art.marks.length} onClick={() => patchArtwork(art.id, undo)} aria-label="撤销" title="撤销 · ⌘ Z"><Icon name="undo" /></button><button disabled={!art.redo.length} onClick={() => patchArtwork(art.id, redo)} aria-label="重做" title="重做 · ⌘ ⇧ Z"><Icon name="redo" /></button><button onClick={() => addArtwork(art)} aria-label="复制后继续创作" title="复制后继续"><Icon name="copy" /></button><button disabled={!hasMarks(art)} onClick={() => keepMark({ id: uid(), tool: 'clear', points: [], color, width: 1, opacity: 1 })} aria-label="清空画布，可撤销" title="清空 · 可以撤销"><Icon name="trash" /></button></div></div>
          <div className="art-canvas-stage"><DrawingSurface key={art.id} art={art} tool={tool} color={color} width={width} opacity={opacity} selecting={selecting} region={region} onRegion={next => { setRegion(next); setSelecting(false); setFocusCanvas(false); setMobilePane('chat'); setPhase('reflection'); composerRef.current?.focus(); }} onMark={keepMark} onUndo={() => patchArtwork(art.id, undo)} onRedo={() => patchArtwork(art.id, redo)} /></div>
          <div className="art-canvas-actions"><button className={selecting || region ? 'art-active-text' : ''} disabled={!hasMarks(art)} onClick={() => { setSelecting(value => !value); setRegion(undefined); }}><Icon name="chat" size={17} />框选画面交流</button><button className="art-dark-button" disabled={!hasMarks(art) || busy} onClick={() => void sendMessage('我想听听你如何观看这幅作品。请结合整体、具体细节和我们此前的交流，自由地谈谈你的感受。',true)}>完成创作，回到对话 <Icon name="arrow" size={17} /></button></div>
          {selecting ? <label className="art-region-options">也可选择位置<select aria-label="选择画面关注位置" defaultValue="" onChange={event => { const boxes: Record<string,Region> = { center:{x:300,y:225,w:600,h:450}, top:{x:0,y:0,w:1200,h:450}, bottom:{x:0,y:450,w:1200,h:450}, left:{x:0,y:0,w:600,h:900}, right:{x:600,y:0,w:600,h:900} }; const next = boxes[event.target.value]; if (next) { setRegion(next); setSelecting(false); setPhase('reflection'); setMobilePane('chat'); } }}><option value="" disabled>选择一处…</option><option value="center">画面中央</option><option value="top">上半部</option><option value="bottom">下半部</option><option value="left">左半部</option><option value="right">右半部</option></select><button onClick={() => setSelecting(false)}>取消</button></label> : null}
          <section className="art-materials" aria-label="材料实验室"><div className="art-material-heading"><span>材料实验室</span><small>{material[tool].note}</small></div><div className="art-material-tools" role="group" aria-label="绘画材料">{TOOLS.map(item => <button key={item} aria-pressed={tool === item} className={tool === item ? 'is-active' : ''} onClick={() => changeTool(item)}><Icon name={item} size={23} /><span>{material[item].name}</span></button>)}</div><div className="art-material-controls"><div className="art-pigments" role="group" aria-label="颜料颜色">{COLORS.map(value => <button key={value} aria-label={'颜料 ' + value} aria-pressed={color === value} className={color === value ? 'is-active' : ''} style={{ backgroundColor:value }} onClick={() => setColor(value)} />)}<label className="art-custom-color" title="自定义颜色"><span>＋</span><input type="color" aria-label="自定义颜料颜色" value={color} onChange={event => setColor(event.target.value)} /></label></div><label className="art-slider-label">笔宽 <input type="range" min="2" max="140" value={width} aria-label="画笔粗细" onChange={event => setWidth(Number(event.target.value))} /><output>{width}</output></label><label className="art-slider-label">浓度 <input type="range" min="10" max="100" value={Math.round(opacity*100)} aria-label="颜料浓度" onChange={event => setOpacity(Number(event.target.value)/100)} /><output>{Math.round(opacity*100)}%</output></label></div><div className="art-paper-row"><span>纸色</span>{PAPERS.map(value => <button key={value} style={{ backgroundColor:value }} aria-label={'纸色 ' + value} aria-pressed={art.paper === value} className={art.paper === value ? 'is-active' : ''} onClick={() => patchArtwork(art.id, current => ({ ...current, paper:value }))} />)}<button className="art-import-art" onClick={() => uploadRef.current?.click()}><Icon name="upload" size={15} />带入自己的作品</button></div></section>
          <div className="art-work-strip" aria-label="这段旅程的作品">{journey.artworks.map((item,index) => <button key={item.id} aria-label={'打开作品 ' + (index+1) + ' ' + item.title} aria-pressed={item.id === activeId} onClick={() => {setActiveId(item.id);setRegion(undefined);}}><ArtPreview art={item} /><span>{String(index+1).padStart(2,'0')}</span></button>)}<button className="art-add-paper" onClick={() => addArtwork()}><Icon name="plus" /><span>新的一张</span></button></div>
        </section> : null}
        {phase === 'reflection' && art ? <section className="art-reflection-work" aria-label="正在交流的作品"><div className="art-reflection-heading"><span className="art-eyebrow">本次旅程</span><h2>作品</h2><p>{works.length} 幅作品 · 点击下方缩略图切换</p></div><div className="art-reflection-image"><ArtPreview art={art} />{region?<div className="art-region-box" style={{left:region.x/WIDTH*100+'%',top:region.y/HEIGHT*100+'%',width:region.w/WIDTH*100+'%',height:region.h/HEIGHT*100+'%'}}><span>正在谈这一处</span></div>:null}</div><h3>{art.title}</h3><div className="art-reflection-actions"><button onClick={()=>goCreate()}><Icon name="ink" />回到画布继续</button><button onClick={()=>{goCreate();setSelecting(true);setRegion(undefined);}}><Icon name="chat" />框选一处聊聊</button><button onClick={()=>void savePng(art)} aria-label="导出当前作品 PNG"><Icon name="download" /></button></div><div className="art-work-strip" aria-label="这段旅程的作品">{works.map(item=><button key={item.id} aria-label={'观看作品 '+item.title} aria-pressed={item.id===activeId} onClick={()=>selectArtwork(item.id)}><ArtPreview art={item} /></button>)}</div></section>:null}
        {phase === 'completed' ? <section className="art-journey-complete"><span className="art-eyebrow">A PAUSE, NOT AN END</span><h1>先把这一刻，<br />留在这里。</h1><p>这段旅程的 {works.length} 幅作品与 {journey.messages.filter(m=>m.content).length} 段交流已留在「我的旅程」。随时回来，接着上次的位置继续。</p><div>{works.slice(-3).map(item=><ArtPreview key={item.id} art={item} />)}</div><nav><button className="art-dark-button" onClick={()=>{setPhase(works.length?'reflection':'dialogue');setMobilePane('chat');}}>继续这段旅程</button><button onClick={()=>setView('gallery')}>整理作品与展览</button><button onClick={beginNewJourney}>开始新的旅程</button><button onClick={exportJourney}>导出这段旅程</button></nav></section>:null}
        {phase !== 'completed' && phase !== 'creating' ? <aside className="art-conversation" aria-label="与 Aether 交流"><header><div><span className="art-ai-orbit" /><strong>Aether</strong><small>与你一起观看</small></div><button onClick={() => setSettings(true)} aria-label="交流偏好"><Icon name="settings" size={18} /></button></header><div className="art-messages">
          {!journey.messages.length ? <div className="art-conversation-welcome"><span className="art-eyebrow">SOUL DIALOGUE</span><h2>我们先聊一会儿。</h2><p>一句说不清的话、一种颜色，或者今天偶然注意到的东西，都可以成为开始。</p><p>此刻你想从哪里开始？不必准确，也不必完整。</p></div> : null}
          {journey.messages.map(message => <article className={'art-message art-message-' + message.role} key={message.id}><div className="art-message-label"><span>{message.role === 'user' ? '你' : 'Aether'}</span>{message.artworkId ? <button onClick={() => selectArtwork(message.artworkId!)}>看这幅作品 ↗</button> : null}</div><p>{message.content || status || '正在观看…'}</p>{message.content ? <button className={'art-keep-quote ' + (exhibition.quotes.includes(message.id) ? 'is-kept' : '')} aria-pressed={exhibition.quotes.includes(message.id)} onClick={() => setExhibition(current => ({ ...current, quotes:toggle(current.quotes,message.id) }))}>{exhibition.quotes.includes(message.id) ? '已留在展览中' : '把这句话留在展览中'}</button> : null}</article>)}
          {invitation ? <div className="art-invitation"><span>一个可以试试的方向</span><h3>{invitation.title}</h3><p>{invitation.prompt}</p><div><button onClick={() => { setBrief(invitation.prompt); if (invitation.action === 'new_artwork') addArtwork(); else goCreate(invitation.prompt); }}>去画画 <Icon name="arrow" size={16} /></button><button onClick={() => setInvitation(null)}>先继续聊</button></div></div> : null}<div ref={bottomRef} />
        </div><form className="art-composer" onSubmit={event => { event.preventDefault(); void sendMessage(draft); }}>{region ? <div className="art-focus-chip"><Icon name="chat" size={14} /><span>带着整幅画，聊聊框选的这一处</span><button type="button" onClick={() => setRegion(undefined)} aria-label="取消画面框选"><Icon name="close" size={14} /></button></div> : null}<textarea ref={composerRef} aria-label="想对 Aether 说的话" placeholder={region ? '这一处，让你想说些什么？' : '让想到的，自然发生…'} value={draft} maxLength={8000} onChange={event => setDraft(event.target.value)} onKeyDown={event => { if ((event.metaKey || event.ctrlKey) && event.key === 'Enter') { event.preventDefault(); void sendMessage(draft); } }} rows={3} /><div><span>{busy ? '正在回应，可以随时停止' : '⌘ / Ctrl + Enter 发送'}</span><button className="art-composer-create" type="button" onClick={()=>goCreate()}>{works.length ? '回到画布' : '我想画画'}</button>{busy ? <button type="button" className="art-send" onClick={stop} aria-label="停止回应">停止</button> : <button className="art-send" type="submit" disabled={!draft.trim()} aria-label="发送给 Aether"><Icon name="arrow" /></button>}</div></form></aside> : null}
      </section> : null}
      {view === 'gallery' ? <section className="art-gallery"><header className="art-gallery-header"><button onClick={() => setView('home')}><Icon name="back" />返回主页</button><div><button onClick={() => importRef.current?.click()}><Icon name="upload" />导入旅程</button><button onClick={exportJourney} disabled={!journey.artworks.length && !journey.messages.length}><Icon name="download" />导出旅程</button></div></header><div className="art-gallery-intro"><div><span className="art-eyebrow">YOUR OPEN COLLECTION</span><h1>作品空间<span> / {String(works.length).padStart(2,'0')}</span></h1><p>一些痕迹，一些还愿意再看一眼的时刻。</p></div><button className="art-dark-button" onClick={() => addArtwork()}><Icon name="plus" />新的一张</button></div><div className="art-collection-note"><span>属于「{session.title}」的作品 · {saveState}</span><button onClick={manageJourneys}>切换旅程 ↗</button><button onClick={()=>enter(false)}>回到这段交流 ↗</button></div><div className="art-gallery-grid">{works.map((item,index) => <article className="art-gallery-card" key={item.id}><button className="art-gallery-image" onClick={() => selectArtwork(item.id)} aria-label={'打开 ' + item.title}><ArtPreview art={item} /><span>继续观看 ↗</span></button><div className="art-gallery-caption"><div><small>{String(index+1).padStart(2,'0')} / {item.origin === 'aether' ? 'AETHER' : 'YOUR HAND'}</small><h2>{item.title || '未命名的片刻'}</h2></div><label><input type="checkbox" checked={exhibition.works.includes(item.id)} onChange={() => setExhibition(current => ({ ...current, works:toggle(current.works,item.id) }))} />入展</label></div></article>)}<button className="art-gallery-empty" onClick={() => addArtwork()}><Icon name="plus" size={32} /><span>{works.length ? '留一点空白，给下一幅。' : '从第一笔开始。'}</span><small>打开材料实验室</small></button></div><section className="art-exhibition-editor"><div><span className="art-eyebrow">MAKE ROOM FOR YOUR WORK</span><h2>为这些片刻，<br />留一间展厅。</h2><p>勾选作品，把对话中想留下的话收入展览。<br />标题和介绍由你决定。</p></div><div><label>展览标题<input value={exhibition.title} maxLength={100} onChange={event => setExhibition(current => ({ ...current,title:event.target.value }))} /></label><label>写在展览前<textarea value={exhibition.note} maxLength={600} rows={3} onChange={event => setExhibition(current => ({ ...current,note:event.target.value }))} /></label><p className="art-selection-count">已选 {exhibition.works.length} 幅作品 · {exhibition.quotes.length} 段对话</p>{savedQuotes.map(message => <div className="art-selected-quote" key={message.id}><p>{message.content}</p><button onClick={() => setExhibition(current => ({ ...current,quotes:current.quotes.filter(id => id !== message.id) }))} aria-label="从展览移除这段话"><Icon name="close" size={14} /></button></div>)}<button className="art-dark-button" disabled={!exhibitWorks.length} onClick={() => { setExhibitIndex(0); setView('exhibition'); }}>进入我的展览 <Icon name="arrow" /></button></div></section></section> : null}
      {view === 'exhibition' ? <section className="art-exhibition"><header><button onClick={() => setView('gallery')}><Icon name="back" />回到作品空间</button><span>AETHER / A PERSONAL EXHIBITION</span><button onClick={() => window.print()}><Icon name="download" />保存为 PDF</button></header><div className="art-exhibition-title"><span className="art-eyebrow">A FEW MOMENTS, HELD HERE</span><h1>{exhibition.title || '一些还没有名字的时刻'}</h1><p>{exhibition.note}</p></div>{exhibitArt ? <div className="art-exhibition-piece"><div className="art-exhibition-mount"><ArtPreview art={exhibitArt} /></div><div className="art-exhibition-label"><div><small>{String(exhibitIndex+1).padStart(2,'0')} / {String(exhibitWorks.length).padStart(2,'0')}</small><h2>{exhibitArt.title}</h2></div><nav aria-label="展览翻页"><button disabled={exhibitIndex === 0} onClick={() => setExhibitIndex(index => Math.max(0,index-1))} aria-label="上一幅"><Icon name="back" /></button><button disabled={exhibitIndex >= exhibitWorks.length-1} onClick={() => setExhibitIndex(index => Math.min(exhibitWorks.length-1,index+1))} aria-label="下一幅"><Icon name="arrow" /></button></nav></div>{savedQuotes.filter(message => !message.artworkId || message.artworkId === exhibitArt.id).map(message => <blockquote key={message.id}>{message.content}<cite>{message.role === 'user' ? '我留下的话' : '与 Aether 的对话'}</cite></blockquote>)}</div> : null}<div className="art-print-exhibition">{exhibitWorks.filter(item => item.id !== exhibitArt?.id).map(item => <section key={item.id}><ArtPreview art={item} /><h2>{item.title}</h2>{savedQuotes.filter(message => message.artworkId === item.id).map(message => <blockquote key={message.id}>{message.content}<cite>{message.role === 'user' ? '我留下的话' : '与 Aether 的对话'}</cite></blockquote>)}</section>)}</div><footer>每一道痕迹，都曾发生。<span>Aether — 灵魂对话</span></footer></section> : null}
    </>}
    {settings ? <div className="art-settings-backdrop"><section ref={dialogRef} className="art-settings" role="dialog" aria-modal="true" aria-labelledby="art-settings-title"><header><h2 id="art-settings-title">按你的节奏。</h2><button onClick={() => setSettings(false)} aria-label="关闭偏好设置"><Icon name="close" /></button></header><p>创作、停留或交谈，都由你决定。</p><label>交流中的提问<select value={questionStyle} onChange={event => setQuestionStyle(event.target.value as typeof questionStyle)}><option value="natural">自然交流，只在有必要时问</option><option value="fewer">少问一些，多谈观看和感受</option><option value="none">不提问，让我自己接着说</option></select></label><div className="art-settings-about"><h3>保留你的旅程</h3><p role="status">{saveState}</p><p>旅程会自动保存在此浏览器，刷新后可以继续。它尚未跨设备同步；换电脑或换网址前，请导出全部旅程，也支持导入上一版的文件。</p><div><button onClick={exportJourney}><Icon name="download" />导出当前旅程</button><button onClick={onExportAll}>导出全部</button><button onClick={() => importRef.current?.click()}><Icon name="upload" />导入旅程</button></div><button onClick={()=>{setSettings(false);manageJourneys();}}>管理所有旅程 ↗</button></div><p className="art-settings-footnote">Aether 是自由创作与作品交流的空间。AI 的观看是一种视角，作品的意义由你保留。</p></section></div> : null}
    {notice || error ? <div className={'art-toast ' + (error ? 'art-toast-error' : '')} role={error ? 'alert' : 'status'}><span>{error || notice}</span><button aria-label="关闭提示" onClick={() => { setError(''); setNotice(''); }}><Icon name="close" size={16} /></button></div> : null}
  </main>;
}
