'use client';
import { useCallback, useEffect, useRef, useState, type ChangeEvent, type ReactNode } from 'react';
import { ArtPreview, Icon } from './art-canvas';
import { createSession, importSessions, loadSessions, saveSessions, sessionBundle, updateSession, type ArtSession } from './art-session-model';
export type SessionProps = { session: ArtSession; initialView: 'home' | 'studio'; saveState: string; onUpdate: (id:string,patch:Partial<ArtSession>)=>void; onManage: ()=>void; onNew: ()=>void; onImport: (event:ChangeEvent<HTMLInputElement>)=>Promise<void>; onExportAll: ()=>void };
function downloadLibrary(sessions:ArtSession[]) { const url=URL.createObjectURL(new Blob([JSON.stringify(sessionBundle(sessions),null,2)],{type:'application/json'})),link=document.createElement('a');link.href=url;link.download='aether-all-journeys.json';link.click();setTimeout(()=>URL.revokeObjectURL(url),1000); }
export default function SessionShell({children}:{children:(props:SessionProps)=>ReactNode}) {
  const [sessions,setSessions]=useState<ArtSession[]>([]),[activeId,setActiveId]=useState(''),[ready,setReady]=useState(false),[entry,setEntry]=useState<'home'|'studio'>('home'),[opening,setOpening]=useState(0);
  const [open,setOpen]=useState(false),[filter,setFilter]=useState<'active'|'archived'|'deleted'>('active'),[search,setSearch]=useState(''),[error,setError]=useState(''),[saveState,setSaveState]=useState('正在恢复旅程…');
  const [storageReady,setStorageReady]=useState(false),[dirty,setDirty]=useState(false);
  const queue=useRef(Promise.resolve()),importRef=useRef<HTMLInputElement>(null),panelRef=useRef<HTMLElement>(null);
  const onUpdate=useCallback((id:string,patch:Partial<ArtSession>)=>{setDirty(true);setSessions(current=>{const item=current.find(s=>s.id===id);return item?updateSession(current,{...item,...patch,id}):current;});},[]);
  useEffect(()=>{let active=true;void loadSessions().then(items=>{if(!active)return;const next=items.length?[...items].sort((a,b)=>b.updatedAt.localeCompare(a.updatedAt)):[createSession()];setSessions(next);setActiveId((next.find(s=>!s.deleted&&!s.archived)||next[0]).id);setStorageReady(true);setSaveState('已保存在此浏览器');}).catch(()=>{if(!active)return;const first=createSession();setSessions([first]);setActiveId(first.id);setSaveState('自动保存不可用，请导出旅程');setError('无法读取此浏览器的旅程存储。现有数据未被覆盖；本次体验请导出保存。');}).finally(()=>{if(active)setReady(true);});return()=>{active=false;};},[]);
  useEffect(()=>{if(!ready||!storageReady)return;let active=true;setSaveState('正在保存…');const timer=setTimeout(()=>{queue.current=queue.current.catch(()=>{}).then(()=>saveSessions(sessions));void queue.current.then(()=>{if(active){setSaveState('已保存在此浏览器');setDirty(false);}}).catch(()=>{if(active){setSaveState('保存失败，请导出旅程');setError('浏览器存储空间不足或不可用。请导出全部旅程，避免丢失。');}});},350);return()=>{active=false;clearTimeout(timer);};},[sessions,ready,storageReady]);
  useEffect(()=>{const warn=(event:BeforeUnloadEvent)=>{if(dirty){event.preventDefault();event.returnValue='';}};window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn);},[dirty]);
  useEffect(()=>{if(!open)return;const previous=document.activeElement instanceof HTMLElement?document.activeElement:null;const items=()=>Array.from(panelRef.current?.querySelectorAll<HTMLElement>('button:not(:disabled),input,select,[tabindex="0"]')||[]);items()[0]?.focus();const key=(event:KeyboardEvent)=>{if(event.key==='Escape')setOpen(false);if(event.key==='Tab'){const list=items(),first=list[0],last=list.at(-1);if(event.shiftKey&&document.activeElement===first){event.preventDefault();last?.focus();}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first?.focus();}}};document.addEventListener('keydown',key);return()=>{document.removeEventListener('keydown',key);if(previous?.isConnected)previous.focus();};},[open]);
  function startNew(){const next=createSession();setSessions(current=>[next,...current]);setActiveId(next.id);setEntry('studio');setOpening(n=>n+1);setOpen(false);setDirty(true);}
  function choose(id:string){setActiveId(id);setEntry('studio');setOpening(n=>n+1);setOpen(false);}
  async function readFile(event:ChangeEvent<HTMLInputElement>){const file=event.target.files?.[0];event.target.value='';if(!file)return;try{if(file.size>80_000_000)throw new Error('请选择 80 MB 以内的旅程文件。');const incoming=importSessions(JSON.parse(await file.text()));if(!incoming.length)throw new Error('文件中没有旅程。');setSessions(current=>[...incoming,...current]);setActiveId(incoming[0].id);setEntry('studio');setOpening(n=>n+1);setOpen(false);setDirty(true);setError('');}catch(err){setError(err instanceof Error?err.message:'旅程导入失败。');}}
  const session=sessions.find(s=>s.id===activeId),visible=sessions.filter(s=>(filter==='deleted'?s.deleted:!s.deleted&&(filter==='archived'?s.archived:!s.archived))&&[s.title,...s.journey.messages.map(m=>m.content)].join(' ').toLowerCase().includes(search.toLowerCase())).sort((a,b)=>Number(b.favorite)-Number(a.favorite)||b.updatedAt.localeCompare(a.updatedAt));
  if(!ready||!session)return <main className="art-app art-loading">Aether · 正在打开你的旅程…</main>;
  return <>{<div key={session.id+'-'+opening} className="art-session-host">{children({session,initialView:entry,saveState,onUpdate,onManage:()=>setOpen(true),onNew:startNew,onImport:readFile,onExportAll:()=>downloadLibrary(sessions)})}</div>}
  <input ref={importRef} type="file" hidden accept=".json,application/json" onChange={readFile} aria-label="导入旅程集合" />
  {open?<div className="art-app art-session-overlay"><button className="art-session-shade" aria-label="关闭旅程列表" onClick={()=>setOpen(false)} /><section ref={panelRef} className="art-session-panel" role="dialog" aria-modal="true" aria-labelledby="session-list-title"><header><div><span className="art-eyebrow">YOUR JOURNEYS</span><h2 id="session-list-title">每一次相遇，都在这里。</h2></div><button onClick={()=>setOpen(false)} aria-label="关闭旅程管理"><Icon name="close" /></button></header><button className="art-dark-button" onClick={startNew}><Icon name="plus" />开始新的旅程</button><input className="art-session-search" aria-label="搜索旅程" placeholder="搜索名称或对话里的话…" value={search} onChange={e=>setSearch(e.target.value)} /><nav aria-label="旅程分类">{(['active','archived','deleted'] as const).map(item=><button key={item} aria-pressed={filter===item} onClick={()=>setFilter(item)}>{item==='active'?'进行中':item==='archived'?'已归档':'最近移除'}</button>)}</nav><div className="art-session-list">{visible.map(item=><article key={item.id} className={item.id===activeId?'is-active':''}><button className="art-session-open" onClick={()=>choose(item.id)} aria-label={'继续旅程 '+item.title}>{item.journey.artworks.find(a=>a.marks.length||a.baseImage)?<ArtPreview art={item.journey.artworks.find(a=>a.marks.length||a.baseImage)!} />:<span className="art-session-glyph">æ</span>}<span><strong>{item.favorite?'★ ':''}{item.title}</strong><small>{item.journey.messages.filter(m=>m.role==='user').at(-1)?.content||'从一句话开始，也可以先停留。'}</small><em>{item.journey.artworks.filter(a=>a.marks.length||a.baseImage).length} 幅作品 · {({dialogue:'交流中',creating:'创作中',reflection:'画后交流',completed:'暂告段落'})[item.phase]}</em></span></button><details><summary>管理这段旅程</summary><label>名称<input aria-label={'重命名旅程 '+item.title} value={item.title} maxLength={100} onChange={e=>onUpdate(item.id,{title:e.target.value})} /></label><div><button onClick={()=>onUpdate(item.id,{favorite:!item.favorite})}>{item.favorite?'取消收藏':'收藏'}</button><button onClick={()=>onUpdate(item.id,{archived:!item.archived})}>{item.archived?'取消归档':'归档'}</button><button onClick={()=>onUpdate(item.id,{deleted:!item.deleted})}>{item.deleted?'恢复旅程':'移至最近移除'}</button></div></details></article>)}{!visible.length?<p className="art-session-empty">这里还没有旅程。每一段对话，都会有自己的位置。</p>:null}</div><footer><p role="status">{saveState}</p><p>在此浏览器自动保存。换电脑或换网址前，导出全部旅程再导入。</p><div><button onClick={()=>downloadLibrary(sessions)}><Icon name="download" />导出全部旅程</button><button onClick={()=>importRef.current?.click()}><Icon name="upload" />导入旅程</button></div></footer></section></div>:null}
  {error?<div className="art-app art-session-error" role="alert"><span>{error}</span><button onClick={()=>downloadLibrary(sessions)}>导出全部</button><button onClick={()=>setError('')} aria-label="关闭存储提示">×</button></div>:null}</>;
}
